Add generic service
stas1408123/GYM pull request #14
Opened 2023-02-13 13:53 UTC by hinkevich

2023-02-13 13:55 UTC, nantonov requested changes

2023-02-13 13:55 UTC, nantonov commented on GymApp/GYM.BLL/Services/GenericService.cs
> +    public class GenericService<TEntity, TModel> : IGymService<TModel>
Should we rename IGymService?

2023-02-13 14:03 UTC, hinkevich commented on GymApp/GYM.BLL/Services/GenericService.cs
> +    public class GenericService<TEntity, TModel> : IGymService<TModel>
new name - IService

2023-02-13 14:06 UTC, Genresal approved these changes

2023-02-13 14:09 UTC, stas1408123 requested changes

2023-02-13 14:09 UTC, stas1408123 commented on GymApp/GYM.BLL/Abstractions/IService.cs
> +public interface IService<TModel> where TModel : class
Rename to IGenericService

2023-02-13 14:18 UTC, stas1408123 approved these changes

2023-02-14 07:56 UTC, stas1408123 approved these changes

2023-02-14 07:56 UTC, nantonov approved these changes

2023-02-14 07:57 UTC, merged