Feature/add models to api
stas1408123/GYM pull request #2
Opened 2023-02-07 15:54 UTC by hinkevich

2023-02-07 16:28 UTC, 5Ka-me commented on GymApp/GymAppApi/Models/CouchVisitor.cs
> +        public Visitor visitor { get; set; }
Separate attributes from links. Add "= null!" or "?" according to relationships in database

2023-02-07 16:28 UTC, 5Ka-me commented on GymApp/GymAppApi/Models/Order.cs
> +        public Visitor Visitor { get; set; }
Add "= null!" or "?" according to relationships in database

2023-02-07 16:28 UTC, 5Ka-me commented on GymApp/GymAppApi/Models/Order.cs
> +        public string Description { get; set; }
Add "= null!" or "?" according to your vision of a model

2023-02-07 16:28 UTC, 5Ka-me commented on GymApp/GymAppApi/Models/Visitor.cs
> +    }
Add attributes or delete empty class

2023-02-07 16:28 UTC, 5Ka-me commented on GymApp/GymAppApi/Models/Couch.cs
> +
Delete empty line

2023-02-07 16:30 UTC, GodlyCat approved these changes

2023-02-07 16:30 UTC, GodlyCat commented on GymApp/GymAppApi/Models/Visitor.cs
> +    public class Visitor
Why this model empty ?

2023-02-07 16:30 UTC, GodlyCat commented on GymApp/GymAppApi/Models/CouchVisitor.cs
> +    public class CouchVisitor
Maybe better to rename this model to Events and maybe better to discuss data structure with your mentor

2023-02-07 16:32 UTC, GodlyCat requested changes
s

2023-02-08 07:02 UTC, stas1408123 approved these changes

2023-02-08 07:30 UTC, hinkevich commented
add changes

2023-02-08 07:48 UTC, hinkevich commented
Add changes

2023-02-08 07:48 UTC, closed without merging

2023-02-08 07:55 UTC, hinkevich commented
Add models