Feature/nmd 296 updete ci di
stas1408123/GYM pull request #23
Opened 2023-02-27 13:21 UTC by hinkevich

2023-02-27 14:59 UTC, stas1408123 requested changes

2023-02-27 14:59 UTC, stas1408123 commented on .github/workflows/dotnet.yml
> +    - name: Restore dependencies
Create different names

2023-02-28 06:41 UTC, stas1408123 approved these changes

2023-02-28 07:30 UTC, Genresal approved these changes

2023-02-28 07:32 UTC, CrazyKamenwik approved these changes

2023-02-28 07:36 UTC, merged