Feature/nmd 305 add policy to authorize request
stas1408123/GYM pull request #31
Opened 2023-03-16 08:02 UTC by hinkevich

2023-03-16 15:10 UTC, stas1408123 approved these changes

2023-03-16 20:51 UTC, nantonov requested changes

2023-03-16 20:51 UTC, nantonov commented on GymApp/GymAppApi/Controllers/CouchesController.cs
> +    [Authorize("AllMethodsAllowed")]
When you use Authorize attribute you can delete thes same attributes from specific endpoints (like your GET endpoint in this controller)
Please, review the rest of endpoints as well

2023-03-17 08:53 UTC, Genresal approved these changes

2023-03-20 13:48 UTC, nantonov approved these changes

2023-03-20 13:50 UTC, merged